version: '3'

services:
  quarkus-desafio:
    image: quarkus/quarkus-desafio:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
#      QUARKUS_PROFILE: dev
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-desafio-quarkus:3306/Pagamentos?autoReconnect=true
    networks:
      - mysql-db
    ports:
      - "8080:8080"
    depends_on:
      - mysql-desafio-quarkus

  mysql-desafio-quarkus:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=wsl
      - MYSQL_USER=usuario-quarkus
      - MYSQL_PASSWORD=Senha12345
      - MYSQL_DATABASE=Pagamentos
    volumes:
      - mysql.desafio.quarkus:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - mysql-db

  prometheus:
    image: prom/prometheus:latest
    container_name: quarkus-desafio-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mysql-db

  grafana:
    image: grafana/grafana
    container_name: quarkus-desafio-grafana
    ports:
      - "3000:3000"
    networks:
      - mysql-db
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  mysql-db:
    driver: bridge

volumes:
  mysql.desafio.quarkus: