global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quarkus-app'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['quarkus-desafio:8080']
        labels:
          env: 'development'
